python3 DatasetsGenerator.py -i cellcycle_FUN
python3 DatasetsGenerator.py -i cellcycle_yeast_FUN
python3 DatasetsGenerator.py -i church_FUN
python3 DatasetsGenerator.py -i church_yeast_FUN
python3 DatasetsGenerator.py -i derisi_FUN
python3 DatasetsGenerator.py -i derisi_yeast_FUN
python3 DatasetsGenerator.py -i diatoms
python3 DatasetsGenerator.py -i eisen_FUN
python3 DatasetsGenerator.py -i eisen_yeast_FUN
python3 DatasetsGenerator.py -i enron
python3 DatasetsGenerator.py -i expression-funcat
python3 DatasetsGenerator.py -i expr_FUN
python3 DatasetsGenerator.py -i expr_yeast_FUN
python3 DatasetsGenerator.py -i exprindiv_ara_FUN
python3 DatasetsGenerator.py -i gasch1_FUN
python3 DatasetsGenerator.py -i gasch1_yeast_FUN
python3 DatasetsGenerator.py -i gasch2_FUN
python3 DatasetsGenerator.py -i gasch2_yeast_FUN
python3 DatasetsGenerator.py -i hom_ara_FUN
python3 DatasetsGenerator.py -i hom_FUN
python3 DatasetsGenerator.py -i hom_yeast_FUN
python3 DatasetsGenerator.py -i imclef07a
python3 DatasetsGenerator.py -i imclef07d
python3 DatasetsGenerator.py -i interpro_ara_FUN
python3 DatasetsGenerator.py -i pheno_FUN
python3 DatasetsGenerator.py -i pheno_yeast_FUN
python3 DatasetsGenerator.py -i reauters
python3 DatasetsGenerator.py -i scop_ara_FUN
python3 DatasetsGenerator.py -i seq_ara_FUN
python3 DatasetsGenerator.py -i seq_FUN
python3 DatasetsGenerator.py -i sequence-funcat
python3 DatasetsGenerator.py -i seq_yeast_FUN
python3 DatasetsGenerator.py -i spo_FUN
python3 DatasetsGenerator.py -i spo_yeast_FUN
python3 DatasetsGenerator.py -i struc_ara_FUN
python3 DatasetsGenerator.py -i struc_FUN
python3 DatasetsGenerator.py -i struc_yeast_FUN
python3 DatasetsGenerator.py -i wipo
