echo "Rodando Cellcycle"
python two_try.py -i "cellcycle_FUN.train.arff"
echo "Rodou Cellcycle 1"
python two_try.py -i "cellcycle_FUN.test.arff"
echo "Rodou Cellcycle 2"
python two_try.py -i "cellcycle_FUN.trainvalid.arff"
echo "Rodou Cellcycle 3"
python two_try.py -i "cellcycle_FUN.valid.arff"
echo "Rodou Cellcycle 4"
echo "Rodando Church"
python two_try.py -i "church_FUN.train.arff"
echo "Rodou Church 1"
python two_try.py -i "church_FUN.test.arff"
echo "Rodou Church 2"
python two_try.py -i "church_FUN.trainvalid.arff"
echo "Rodou Church 3"
python two_try.py -i "church_FUN.valid.arff"
echo "Rodou Church 4"
echo "Rodando Derisi"
python two_try.py -i "derisi_FUN.train.arff"
echo "Rodou Derisi 1"
python two_try.py -i "derisi_FUN.test.arff"
echo "Rodou Derisi 2"
python two_try.py -i "derisi_FUN.trainvalid.arff"
echo "Rodou Derisi 3"
python two_try.py -i "derisi_FUN.valid.arff"
echo "Rodou Derisi 1"
echo "Rodando Eisen"
python two_try.py -i "eisen_FUN.train.arff"
echo "Rodou Eisen 1"
python two_try.py -i "eisen_FUN.test.arff"
echo "Rodou Eisen 2"
python two_try.py -i "eisen_FUN.trainvalid.arff"
echo "Rodou Eisen 3"
python two_try.py -i "eisen_FUN.valid.arff"
echo "Rodou Eisen 4"
